name: BaseCommands
main: com.github.catchaser.BaseCommands
version: 2.0.4
description:  >
             Basic Commands for a bukkit server
Author: catchaser9620
Tester: sh4nks
commands:
    heal:
      description: Heals the/a player
    tp:
      description: Teleports the player 
    tphere:
      description: Teleports a player to your current location
    ginfo:
     description: Gathers info about the/a player
    ginfo2:
     description: Gathers the other part of the/a players info
    fly:
     description: Enables Flying
    dfly:
     description: Disables Flying
    spawn:
     description: Teleports player to the spawn location in the current world
    setspawn:
     description: Sets the spawn location in a world
    whoiso:
     description: Displays all the players who are online (Still in development)
    rules:
     description: Displays the rules
    home:
     description: Teleports player to where they set their home
    sethome:
     description: Sets the home of the players current location
    setwarp:
     description: Sets the warp of the current players location
    warp:
     description: Teleports player to warp
    delwarp:
     description: Deletes a warp
    time:
     description: Changes the time
    weather:
     description: Changes the weather
    kill:
     description: Kills a/the player
    kick:
     description: kicks a player
    Ban:
     description: Bans a player from the server
    unban:
     description: Unbans a player
    nickname:
     description: gives the player a nickname
    unnick:
     description: unicknames a player
    bcversion:
     description: Checks the version of both BaseCommands and Bukkit
    feed:
     description: Feeds the/a player
    msg:
     description: sends a message to a player
    freeze:
     description: freezes a player
    unfreeze:
     description: unfreezes a player
permissions:
  BC.*:
     decription: gives all BaseCommands Permissions
     children:
             BC.admin.*: true
             BC.warp.*: true
             BC.who.*: true
             BC.home.*: true
             BC.heal.*: true
             BC.tp.*: true
             BC.flight.*: true
             BC.env.*: true
             BC.name.*: true
  BC.warp.*:
    description: Allows a player to use all the BC warp commands
    children:
            BC.warp.warp: true
            BC.warp.setwarp: true
            BC.warp.delwarp: true
  BC.warp.warp:
        description: Allows plays to warp
        default: op
  BC.warp.setwarp:
        description: Allows players to create warps
        default: op
  BC.warp.delwarp:
        description: Allows players to delete warps
        default: op
  BC.home.*:
    description: Allows a player to use all home/spawn commands
    children:
            BC.home.spawn: true
            BC.home.setspawn: true
            BC.home.sethome: true
            BC.home.home: true
  BC.home.spawn:
        description: Allows a player to teleport to spawn
        default: true
  BC.home.setspawn:
        description: Allows a player to set the current location of spawn
        default: op
  BC.home.sethome:
        description: Allows a player to set thier home location
        default: op
  BC.home.home:
        description: Allows a player to go home
        default: op
  BC.who.*:
    description: Allows all who/msg commands
    children:
            BC.who.iso: true
            BC.who.msg: true
  BC.who.iso:
        description: Allows a player to check who is online
        default: op
  BC.who.msg:
        description: sends a msg to a player
        default: op
  BC.heal.*:
        description: Allows a player to use all the heal commands
        children:
                BC.heal.self: true
                BC.heal.other: true
                BC.heal.kill: true
                BC.heal.feed: true
  BC.heal.self:
        description: Allows a plyaer to heal them self
        default: op
  BC.heal.other:
        description: Allows a player to heal another player
        default: op
  BC.heal.kill:
         description: Allows a player to kill another player or them self
         default: op
  BC.heal.feed:
         description: Allows a player to feed him/her self or another player
         default: op
  BC.tp.*:
    description: Allows a player to use all tp commands
    children:
            BC.tp.2p: true
            BC.tp.p2p: true
            BC.tp.here: true
  BC.tp.2p:
       description: Teleports the current player to another player
       default: op
  BC.tp.p2p:
       description: Teleports a player to another player
       default: op
  BC.tp.here:
       description: Teleports a player to the current player
       default: op
  BC.flight.*:
    description: Allows all flight commands
    children:
            BC.flight.fly: true
            BC.flight.dfly: true
  BC.flight.fly:
          description: Allows a player to fly
          default: op
  BC.flight.dfly:
          description: Disables flight for player
          default: op
  BC.env.*:
        description: Allows a player to use all the enviorment commands
        children:
                BC.env.time: true
                BC.env.weather: true
  BC.env.time:
       description: Allows a player to change the time
       default: op
  BC.env.weather:
       description: Allows a player to change the weather
       default: op   
  BC.admin.*:
    description: Allows a player to use the 3 player commands kick ban and unban
    children:
            BC.admin.kick: true
            BC.admin.ban: true
            BC.admin.unban: true
            BC.admin.freeze: true
            BC.admin.unfreeze: true
  BC.admin.kick:
         description: Allows the kick command
         default: op
  BC.admin.ban:
         description: Allows the ban command
         default: op
  BC.admin.unban:
         description: Allows the unban command
         default: op
  BC.admin.freeze:
         description: freezes the player
         default: op
  BC.admin.unfreeze:
         description: unfreezes a player
         default: op
  BC.name.*:
    description: Allows all nickname commands
    children:
            BC.name.nick: true
            BC.name.unnick: true
  BC.name.nick:
         description: Allows the nickname command
         default: op
  BC.name.unnick:
         description: Allows the unnick command
         default: op